name: 1Password Test
on:
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install 1Password CLI
        run: |
          curl -o "op.zip" "https://cache.agilebits.com/dist/1P/op2/pkg/v2.18.0-beta.01/op_linux_amd64_v2.18.0-beta.01.zip"
          unzip op.zip
          chmod +x op
      - name: Test authentication
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        run: ./op user get --me
